# app/exceptions.py

#

# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

class ValidationError(ValueError):
    pass